# 构建 VitePress 站点并将其部署到另一个 GitHub 仓库的示例工作流程
name: Deploy VitePress site to Another Repo

on:
  # 在针对 `main` 分支的推送上运行。如果你
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches: [main]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      # - uses: oven-sh/setup-bun@v1 # 如果使用 Bun，请取消注释
      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # 如果使用 pnpm，请取消注释
        with:
          version: 9.1.3
      - name: Print PATH
        run: echo $PATH
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm # npm 或 pnpm / yarn
      - name: Install dependencies
        run: pnpm install # npm ci 或 pnpm install / yarn install / bun install
      - name: Build with VitePress
        run: pnpm build # npm run docs:build 或 pnpm docs:build / yarn docs:build / bun run docs:build

      # 部署工作
      - name: Checkout target repo
        run: |
          mkdir target-repo
          cd target-repo
          git config --global init.defaultBranch main
          git init
          git remote add targetOrigin git@github.com:Yuhemei/blogs.git
          git pull targetOrigin main || true
      - name: Sync built files to target repo
        run: |
          rsync -av --delete docs/.vitepress/dist/ target-repo/
      - name: Deploy to Another Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh -T git@github.com || true  # 添加这一行来验证 SSH 配置

          cd target-repo
          git config  user.name 'kim'
          git config  user.email 'yuhemei8088@163.com'
          git add .
          git commit -m 'Deploy VitePress site'
          git push -f targetOrigin main
