name: Deploy VitePress site to Another Repo

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.1.3

      - name: Print PATH
        run: echo $PATH

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build with VitePress
        run: pnpm build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh -T git@github.com || true  # 验证 SSH 配置

      - name: Checkout target repo
        run: |
          mkdir target-repo
          cd target-repo
          git init
          git config  user.email "yuhemei8088@163.com"
          git config  user.name "yuhemei"
          git remote add origin git@github.com:Yuhemei/blogs.git
          git pull origin main || true  # 忽略错误以确保后续步骤可以运行

      - name: Sync built files to target repo
        run: |
          rsync -av --delete docs/.vitepress/dist/ target-repo/
          cd target-repo
          git add .
          git commit -m 'Deploy VitePress site'
          git push origin main
